export const surveyCategories = [
  {
    id: "identity-access",
    name: "Identity, Access & Security Governance",
    questions: [
      {
        id: "iam-sso",
        type: "radio",
        question: "How is employee access to AI tools managed today?",
        options: [
          { label: "No centralized control — employees sign up individually", score: 1 },
          { label: "Some tools gated behind SSO, but many ungoverned", score: 2 },
          { label: "SSO and MFA enforced for all AI tools", score: 3.5 },
          { label: "SSO + MFA + role-based access policies for AI tools", score: 4.5 },
          { label: "Fully governed with automated provisioning, deprovisioning, and audit trails", score: 6 },
        ],
      },
      {
        id: "iam-policy",
        type: "radio",
        question: "Does your organization have an AI acceptable use policy?",
        options: [
          { label: "No policy exists", score: 1 },
          { label: "Informal guidelines shared verbally or in Slack", score: 2 },
          { label: "Written policy exists but is not enforced", score: 3 },
          { label: "Policy is enforced with tooling controls", score: 4.5 },
          { label: "Policy is enforced, audited, and regularly updated", score: 6 },
        ],
      },
      {
        id: "iam-secrets",
        type: "radio",
        question: "How are API keys and service credentials managed?",
        options: [
          { label: "Embedded in code or shared via chat", score: 1 },
          { label: "Stored in environment variables, no rotation", score: 2 },
          { label: "Centralized secrets manager (Vault, AWS Secrets Manager, etc.)", score: 4 },
          { label: "Centralized, rotated automatically, with audit logging", score: 5.5 },
        ],
      },
    ],
  },
  {
    id: "cicd",
    name: "CI/CD Pipeline Maturity",
    questions: [
      {
        id: "cicd-pipeline",
        type: "radio",
        question: "What does your CI/CD pipeline look like today?",
        options: [
          { label: "No automated pipeline — manual builds and deploys", score: 1 },
          { label: "Basic pipeline — automated build only", score: 2 },
          { label: "Build + lint + basic test gates on every PR", score: 3 },
          { label: "Enforced gates with coverage thresholds and required checks", score: 4.5 },
          { label: "Machine-readable output, self-healing capable, high concurrency", score: 6 },
        ],
      },
      {
        id: "cicd-branch",
        type: "radio",
        question: "Are branch protection rules enforced?",
        options: [
          { label: "No branch protection — anyone can push to main", score: 1 },
          { label: "Branch protection exists but can be bypassed", score: 2.5 },
          { label: "Required reviews and CI checks before merge", score: 4 },
          { label: "Strict protection with required checks, no bypass for anyone", score: 5.5 },
        ],
      },
      {
        id: "cicd-deploy",
        type: "radio",
        question: "How are deployments handled?",
        options: [
          { label: "Manual deployment process (FTP, RDP, manual scripts)", score: 1 },
          { label: "Semi-automated — scripts exist but run manually", score: 2 },
          { label: "Automated deployment on merge to main", score: 3.5 },
          { label: "Blue/green or canary deploys with automated rollback", score: 5 },
          { label: "Fully automated with infrastructure-as-code and GitOps", score: 6 },
        ],
      },
    ],
  },
  {
    id: "cloud-infra",
    name: "Cloud Infrastructure & Containerization",
    questions: [
      {
        id: "cloud-state",
        type: "radio",
        question: "What best describes your infrastructure today?",
        options: [
          { label: "Primarily on-premise servers", score: 1 },
          { label: "Hybrid — some workloads in cloud, core on-prem", score: 2.5 },
          { label: "Cloud-first — most workloads in AWS, Azure, or GCP", score: 4 },
          { label: "Cloud-native with containerized microservices", score: 5.5 },
        ],
      },
      {
        id: "cloud-tools",
        type: "checkbox",
        question: "Which of these are in use today? (Select all that apply)",
        options: [
          { label: "Docker containers", value: "docker" },
          { label: "Kubernetes or managed container orchestration", value: "k8s" },
          { label: "Infrastructure-as-Code (Terraform, Pulumi, CloudFormation)", value: "iac" },
          { label: "Serverless functions (Lambda, Azure Functions)", value: "serverless" },
          { label: "Container registry (ECR, ACR, GCR)", value: "registry" },
        ],
      },
      {
        id: "cloud-isolation",
        type: "radio",
        question: "Can you spin up isolated environments on demand?",
        options: [
          { label: "No — shared dev/staging servers only", score: 1 },
          { label: "Can create VMs manually but it takes hours/days", score: 2 },
          { label: "Automated environment creation in minutes", score: 4 },
          { label: "Ephemeral environments spin up in seconds per task", score: 6 },
        ],
      },
    ],
  },
  {
    id: "platform-modernity",
    name: "Platform Modernity & Legacy Debt",
    questions: [
      {
        id: "platform-stack",
        type: "radio",
        question: "What describes your primary tech stack?",
        options: [
          { label: "Legacy languages (COBOL, VB6, classic ASP, Fortran)", score: 1 },
          { label: "Older but supported frameworks (.NET Framework, Java 8, jQuery)", score: 2 },
          { label: "Modern mainstream (React, .NET Core, Spring Boot, Python 3)", score: 4 },
          { label: "Current-generation with modern architecture patterns", score: 5.5 },
        ],
      },
      {
        id: "platform-monolith",
        type: "radio",
        question: "How monolithic are your core systems?",
        options: [
          { label: "Single large monolith with no service boundaries", score: 1 },
          { label: "Monolith with some extracted services", score: 2.5 },
          { label: "Service-oriented with clear API boundaries", score: 4 },
          { label: "Microservices with well-defined domains", score: 5.5 },
        ],
      },
      {
        id: "platform-legacy-pct",
        type: "slider",
        question: "What percentage of your codebase is on modern, actively-maintained frameworks?",
        min: 0,
        max: 100,
        step: 5,
        unit: "%",
        thresholds: [
          { max: 20, score: 1 },
          { max: 40, score: 2 },
          { max: 60, score: 3 },
          { max: 80, score: 4.5 },
          { max: 100, score: 6 },
        ],
      },
    ],
  },
  {
    id: "testing-qa",
    name: "Testing & Quality Assurance",
    questions: [
      {
        id: "testing-coverage",
        type: "radio",
        question: "What is the state of automated testing?",
        options: [
          { label: "No automated tests", score: 1 },
          { label: "Some unit tests, no CI integration", score: 2 },
          { label: "Unit + integration tests running in CI", score: 3.5 },
          { label: "High coverage with enforced thresholds in CI", score: 5 },
          { label: "Comprehensive suite with near-zero flakiness, intelligent test selection", score: 6 },
        ],
      },
      {
        id: "testing-coverage-pct",
        type: "slider",
        question: "Estimated test coverage across critical code paths?",
        min: 0,
        max: 100,
        step: 5,
        unit: "%",
        thresholds: [
          { max: 10, score: 1 },
          { max: 30, score: 2 },
          { max: 50, score: 3 },
          { max: 75, score: 4.5 },
          { max: 100, score: 6 },
        ],
      },
      {
        id: "testing-flaky",
        type: "radio",
        question: "How reliable is your test suite?",
        options: [
          { label: "Tests fail randomly — results are not trusted", score: 1 },
          { label: "Some flaky tests, team re-runs to get green", score: 2 },
          { label: "Mostly reliable with occasional flakes", score: 3.5 },
          { label: "Highly reliable — flaky tests are tracked and fixed promptly", score: 5 },
          { label: "Near-zero flakiness — suite is a trusted gate", score: 6 },
        ],
      },
    ],
  },
  {
    id: "api-integration",
    name: "API Surface & Integration Readiness",
    questions: [
      {
        id: "api-surface",
        type: "radio",
        question: "Do core internal systems expose APIs?",
        options: [
          { label: "No — internal systems are closed with no API access", score: 1 },
          { label: "Some systems have APIs, but undocumented or inconsistent", score: 2 },
          { label: "Core systems expose documented REST or GraphQL APIs", score: 4 },
          { label: "Full API surface with versioning, documentation, and rate limiting", score: 5.5 },
        ],
      },
      {
        id: "api-patterns",
        type: "checkbox",
        question: "Which integration patterns are in use? (Select all that apply)",
        options: [
          { label: "REST APIs", value: "rest" },
          { label: "GraphQL", value: "graphql" },
          { label: "Event-driven / message queues (Kafka, SQS, RabbitMQ)", value: "events" },
          { label: "Webhooks", value: "webhooks" },
          { label: "gRPC or similar RPC protocols", value: "grpc" },
        ],
      },
      {
        id: "api-docs",
        type: "radio",
        question: "How well are your APIs documented?",
        options: [
          { label: "No documentation", score: 1 },
          { label: "Some docs exist but are outdated or incomplete", score: 2 },
          { label: "OpenAPI / Swagger specs for most endpoints", score: 4 },
          { label: "Auto-generated, versioned documentation with examples and SDKs", score: 6 },
        ],
      },
    ],
  },
  {
    id: "observability-agentic",
    name: "Observability & Agentic Workflows",
    questions: [
      {
        id: "obs-state",
        type: "radio",
        question: "What is your observability posture?",
        options: [
          { label: "Minimal logging — console.log or basic file logs", score: 1 },
          { label: "Centralized logging but no tracing or metrics", score: 2 },
          { label: "Structured logging + basic metrics dashboards", score: 3 },
          { label: "Full observability — logs, traces, metrics with alerting", score: 5 },
          { label: "AI-pipeline-aware observability with retrieval quality tracking", score: 6 },
        ],
      },
      {
        id: "obs-agentic",
        type: "checkbox",
        question: "Which agentic capabilities exist today? (Select all that apply)",
        options: [
          { label: "MCP server exposing internal tools", value: "mcp" },
          { label: "AI retrieval pipelines (RAG) over internal data", value: "rag" },
          { label: "Agentic workflows with multi-step execution", value: "workflows" },
          { label: "Human-in-the-loop approval gates for AI actions", value: "hitl" },
          { label: "Vector database for semantic search", value: "vectordb" },
        ],
      },
      {
        id: "obs-maturity",
        type: "slider",
        question: "Rate your organization's overall agentic AI maturity (0 = none, 10 = fleet-scale)",
        min: 0,
        max: 10,
        step: 1,
        unit: "",
        thresholds: [
          { max: 1, score: 1 },
          { max: 3, score: 2 },
          { max: 5, score: 3 },
          { max: 7, score: 4.5 },
          { max: 10, score: 6 },
        ],
      },
    ],
  },
];
